Revert "calibre: version bumped to 0.9.12."
This reverts commit ded86cce4fa8a3fa95197772108040666e20a60a.

The make fails on;

  fatal error: private/qtextengine_p.h: No such file or directory

The only mention of that header is in the qt_hack.cpp file. The qtextengine_p.h
file does not exist in this tarball.